services:
  postiz:
    environment:
      MAIN_URL: '${PUBLIC_BASE_URL:?PUBLIC_BASE_URL is required.}'
      FRONTEND_URL: '${PUBLIC_BASE_URL:?PUBLIC_BASE_URL is required.}'
      NEXT_PUBLIC_BACKEND_URL: '${PUBLIC_BACKEND_URL:?PUBLIC_BACKEND_URL is required.}'
      X_URL: '${PUBLIC_BASE_URL:?PUBLIC_BASE_URL is required.}'
      ALLOW_PUBLIC_DOMAIN_WITH_LOCAL_DB: 'true'
